theme: jekyll-theme-cayman
title: KwangEun An 
search_in_sidebar: true

# inserts github link below page title
github_button_location_below_title: true

# inserts github link at bottom of page (least visible)
github_button_location_page_bottom: true